baseurl = "https://yuhi-sa.github.io/"
DefaultContentLanguage = "ja"
title = "tomato blog"
theme = "tomatohugo"
metaDataFormat = "yaml"

author = false

enableRobotsTXT = true

GoogleAnalytics = "G-LN6QP6VVM3"
GoogleAdClientId = "ca-pub-9558545098866170"

pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true


[languages]
  [languages.ja]
    languageName = "Japanese"
  [languages.en]
    languageName = "English"

[Params]
  # subtitle = "yuhi-sa"
  favicon = "img/icon.JPG"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = true
  readingTime = false
  wordCount = false
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true

[Author]
  name = "yuhi-sa"

[[menu.main]]
  name = "Blog"
  url = ""
  weight = 1

[[menu.main]]
  name = "Tags"
  url = "tags"
  weight = 2

[[menu.main]]
  name = "About"
  url = "posts/about"
  weight = 3

[[menu.main]]
  name = "privacy policy"
  url = "posts/privacy_policy"
  weight = 4
