[params]
# Basig Configuration
baseurl = "https://yuhi-sa.github.io/"
title = "tomato blog"
theme = "tomatohugo"

# Google Analytics Configuration
googleAnalytics = "G-LN6QP6VVM3"

# Google Adsense Configuration
googleAdClientId = "ca-pub-9558545098866170"

# Robots.txt Configuration
enableRobotsTXT = true

# Code Highlighting Configuration
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Lamguage Configuration
DefaultContentLanguage = "ja"
[languages]
  [languages.ja]
    languageName = "Japanese"
  [languages.en]
    languageName = "English"

# Manu Configuration
[[menu.main]]
  name = "Blog"
  url = ""
  weight = 1

[[menu.main]]
  name = "Tags"
  url = "tags"
  weight = 2

[[menu.main]]
  name = "About"
  url = "posts/about"
  weight = 3

[[menu.main]]
name = "privacy policy"
url = "posts/privacy_policy"
weight = 6
