
baseurl = "https://yuhi-sa.github.io/"
title = "tomato blog"
theme = "tomatohugo"
disqusShortname = "yuhu-sa"
DefaultContentLanguage = "ja"

enableRobotsTXT = true

pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

paginate = 5

[params]
  googleAnalyticsID = "G-LN6QP6VVM3"
  adsenseClientID = "ca-pub-9558545098866170"

[languages]
  [languages.ja]
    languageName = "Japanese"
  [languages.en]
    languageName = "English"

[[menu.main]]
  name = "Blog"
  url = ""
  weight = 1

[[menu.main]]
  name = "Tags"
  url = "tags"
  weight = 2

[[menu.main]]
  name = "About"
  url = "posts/about"
  weight = 3

[[menu.main]]
name = "Privacy policy"
url = "posts/privacy_policy"
weight = 6
