baseurl = "https://yuhi-sa.github.io/"
DefaultContentLanguage = "en"
title = "@yuhi-sa"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
author = false
googleAnalytics = "G-LN6QP6VVM3"
enableRobotsTXT = true

[Params]
  # subtitle = "yuhi-sa"
  # logo = "img/icon.JPG" # Expecting square dimensions
  favicon = "img/icon.JPG"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = true
  readingTime = false
  wordCount = false
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true


[Author]
  name = "yuhi-sa"
  github = "yuhi-sa"

[[menu.main]]
  name = "Blog"
  url = ""
  weight = 1

[[menu.main]]
  name = "Tags"
  url = "tags"
  weight = 2

[[menu.main]]
  name = "About"
  url = "posts/about"
  weight = 3