
baseurl = "https://yuhi-sa.github.io/"
title = "tomato blog"
theme = "tomatohugo"

googleAnalytics = "G-LN6QP6VVM3"
googleAdsense = "ca-pub-3940256099942544"

enableRobotsTXT = true

pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

DefaultContentLanguage = "ja"
[languages]
  [languages.ja]
    languageName = "Japanese"
  [languages.en]
    languageName = "English"

[[menu.main]]
  name = "Blog"
  url = ""
  weight = 1

[[menu.main]]
  name = "Tags"
  url = "tags"
  weight = 2

[[menu.main]]
  name = "About"
  url = "posts/about"
  weight = 3

[[menu.main]]
name = "privacy policy"
url = "posts/privacy_policy"
weight = 6
