name: Create Card

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: publish
      run: |
        cd public
        git config user.name "<git-user-name>"
        git config user.email "<git-user-e-mail>"
        git add *
        git commit -m "Update"
        git push origin master
